name: unicode_sanity_checks
on: [pull_request]

jobs:
  scan_unicode:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          token: ${{ secrets.GH_PAT }}
      - name: Set git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          echo "✔ Git identity set to $(git config --global user.name) <$(git config --global user.email)>"
      - name: Detect non-ASCII characters
        run: |
          if git diff origin/main...HEAD | grep -P '[^\x00-\x7F]'; then
            echo '::warning title=Unicode Warning::Non-ASCII characters found (including CJK/homoglyphs)'
          fi
      - name: Detect Trojan-Source control chars
        run: |
          if git diff origin/main...HEAD | grep -P '[\u202A-\u202E\u2066-\u2069]'; then
            echo '::error title=Trojan Source::Bidirectional unicode attack characters found!'
            exit 1
          fi
