name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          token: ${{ secrets.GH_PAT }}
      - name: Check branch sync with main
        run: |
          git fetch origin main
          git merge --no-commit --allow-unrelated-histories origin/main || {
            echo '❌ Branch is stale; please merge/rebase main manually and resolve conflicts.'
            exit 1
          }
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run sanitizers and tests
        run: |
          find . -name '*.py' -exec python3 ci/remove_cjk.py {} +
          find . -name '*.py' -exec python3 ci/remove_bidi.py {} +
          pytest --maxfail=1 --disable-warnings -q
      - name: Push sanitized/tested code
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: ${{ github.head_ref }}
      - name: Auto-merge PR after CI
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          merge-method: merge
          merge-labels: automerge
