name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run sanitizers
        run: |
          python ci/remove_cjk.py $(git ls-files '*.py' '*.yml' '*.md') || true
          python ci/remove_bidi.py $(git ls-files '*.py' '*.yml' '*.md') || true
      - name: Run tests
        run: pytest -q
      - name: Commit sanitized files
        run: |
          git config user.email "action@github.com"
          git config user.name "github-actions"
          git diff --quiet || git commit -am "chore: sanitize unicode"
      - name: Push changes
        if: github.event_name == 'push'
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git push https://$GH_PAT@github.com/${{ github.repository }} HEAD:${{ github.ref }}
