name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          token: ${{ secrets.GH_PAT }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run sanitizers and tests
        run: |
          find . -name '*.py' -exec python3 ci/remove_cjk.py {} +
          find . -name '*.py' -exec python3 ci/remove_bidi.py {} +
          pytest --maxfail=1 --disable-warnings -q
      - name: Push changes to protected branch
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: ${{ github.head_ref }}
